# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.10.0"

pre_release = true

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.12.35
Kubernetes: 1.33.1
runc: 1.3.0
containerd: 2.1.3
Flannel CNI plugin: 1.7.1-flannel1
Flannel: 0.27.0

Talos is built with Go 1.24.4.
"""

    [notes.macos-qemu]
        title = "Qemu provisioner on MacOS"
                description = """\
On MacOS `talosctl cluster create` command now supports the Qemu provisioner in addition to the Docker provisioner.
"""

    [notes.ima]
        title = "IMA support removed"
        description = """\
Talos now drops the IMA (Integrity Measurement Architecture) support. This feature was not used in Talos for any meaningful security purpose
and has historically caused performance issues. See #11133 for more details.
"""

    [notes.swap]
        title = "Swap Suport"
        description = """\
Talos now supports swap on block devices.
This feature can be enable by using [SwapVolumeConfig](https://www.talos.dev/v1.11/reference/configuration/block/swapvolumeconfig/) document in the machine configuration.  
"""

    [notes.vmware]
        title = "VMware"
        description = """\
Talos VMWare platform now supports `arm64` architecture in addition to `amd64`.
"""

    [notes.azure]
        title = "Azure"
        description = """\
Talos on Azure now defaults to MTU of 1400 bytes for the `eth0` interface to avoid packet fragmentation issues.
The default MTU can be overriden with machine configuration.
"""

    [notes.k8s_version]
        title = "Kubernetes Version Validation"
        description = """\
Talos now validates Kubernetes version in the image submitted in the machine configuration.
Previously this check was performed only on upgrade, but now it is consistently applied to upgrade, initial provisioning, and machine configuration updates.

This implies that all image references should contain the tag, even if the image is pinned by digest.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
